import Head from "next/head";
import Conteudo from "./Conteudo";
import MenuLateral from "./MenuLateral";
import Titulo from "./Titulo";

interface Props {
  titulo: string;
  subtitulo: string;
  children?: any;
}

export default function Layout(props: Props) {
  return (
    <>
      <Head>
        <title>Admin Template</title>
        <meta name="description" content="Generated by Helton" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen w-screen">
        <MenuLateral />
        <div className="flex flex-col w-full p-7 bg-gray-300">
          <Titulo {...props} />
          <Conteudo>{props.children}</Conteudo>
        </div>
      </div>
    </>
  );
}
