import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Admin Template</title>
        <meta name="description" content="Generated by Helton" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
