import Head from "next/head";
import Layout from "../components/template/Layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Admin Template</title>
        <meta name="description" content="Generated by Helton" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout titulo="Título" subtitulo="Subtítulo">
        Conteúdo
      </Layout>
    </>
  );
}
